Testing async blog post
alanvardy/alan_vardy pull request #72
Opened 2022-09-16 14:42 UTC by alanvardy

2022-09-16 14:42 UTC, alanvardy commented
Current dependencies on/for this PR:
* main
  * **PR #72** <a href="https://app.graphite.dev/github/pr/alanvardy/alan_vardy/72" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/alanvardy/alan_vardy/72?utm_source=stack-comment).

2022-09-18 16:52 UTC, CorneliaKelinske requested changes
I find this article super interesting. It could be a bit clear and easier to follow.

2022-09-18 16:52 UTC, CorneliaKelinske commented on posts/2022/09-15-testing-async.md
> +```
Where does this code live? in which file?

2022-09-18 16:52 UTC, CorneliaKelinske commented on posts/2022/09-15-testing-async.md
> +When starting up the async process in `start_supervised!/2`, pass in the PID of the test process and use that for all repo calls. You can see an example of this in the last section.
how do i get the test_pid?
Is it just:

setup do
  start_supervised!({SomeProcess, test_pid})
end

?

2022-09-18 16:52 UTC, CorneliaKelinske commented on posts/2022/09-15-testing-async.md
> +
Where does this code live?

Also: might be worth showing where you use the message sending in a test.
I find the article super interesting, but I'm not sure if I would be readily able to test that way based on the description in this post.

Can you include a full example below the text? Where it is all put together?

So something like:
Filename:
```code```

filename:
```code```

If that makes sense?

2022-09-18 18:55 UTC, alanvardy commented
Thank you Cornelia, I think I addressed your questions

2022-09-18 19:03 UTC, CorneliaKelinske approved these changes

2022-09-18 19:17 UTC, merged